env:
  - HUGO_VERSION="0.40.3"

install:
  - wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.tar.gz
  - mkdir /tmp/hugo
  - tar xvfz -C /tmp/hugo /tmp/hugo.tar.gz
  - export PATH=$PATH:/tmp/hugo

script:
  - /tmp/hugo/hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
