backend:
  name: github
  repo: e3b0c442/osc-website
  branch: master # Branch to update (optional; defaults to master)
  site_domain: hardcore-dijkstra-fb6a87.netlify.com

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "banner"
    label: "Banner"
    folder: "content/banner"
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
